name: Sanity Check

on:
  push:
    branches:
      - main
    paths:
      - 'cypress/**'
      - '.github/workflows/sanity-check.yml'
      - '.cypress-cucumber-preprocessorrc.json'
      - 'cypress.config.js'
      - 'package-lock.json'
      - 'package.json'
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  test:
    name: Sanity Tests - local - electron
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      rbp-booking:
        image: mwinteringham/restfulbookerplatform_booking:1.6.24c7b22
        ports:
          - 3000:3000
      rbp-room:
        image: mwinteringham/restfulbookerplatform_room:1.6.24c7b22
        ports:
          - 3001:3001
      rbp-branding:
        image: mwinteringham/restfulbookerplatform_branding:1.6.24c7b22
        ports:
          - 3002:3002
      rbp-assets:
        image: mwinteringham/restfulbookerplatform_assets:1.6.24c7b22
        ports:
          - 3003:3003
      rbp-auth:
        image: mwinteringham/restfulbookerplatform_auth:1.6.24c7b22
        ports:
          - 3004:3004
      rbp-report:
        image: mwinteringham/restfulbookerplatform_report:1.6.24c7b22
        ports:
          - 3005:3005
      rbp-message:
        image: mwinteringham/restfulbookerplatform_message:1.6.24c7b22
        ports:
          - 3006:3006
      rbp-proxy:
        image: mwinteringham/restfulbookerplatform_proxy:latest
        ports:
          - 80:80
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Cypress Run
        id: cypress-run
        uses: cypress-io/github-action@v6
        with:
          env: ENV=local,TAGS=@sanity and not @bug
          browser: electron
          command-prefix: '--'
      - name: Generate Allure Report
        id: generate-allure-report
        run: |
          npx allure generate --single-file cypress/reports/allure-results -o cypress/reports/allure-report-html --clean
      - name: Upload Cucumber Report
        id: upload-cucumber-report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-report
          path: cypress/reports/html
          retention-days: 1
      - name: Upload Allure Report
        id: upload-allure-report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: cypress/reports/allure-report-html
          retention-days: 1
