name: Trigger Playwright Tests
on:
  push:
    branches: 
      - main

jobs:
  trigger-playwright-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright Tests
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository_owner }}/playwright-e2e-tests/dispatches \
            -d '{"event_type":"run-pw-tests","client_payload":{"cy_commit_sha":"${{ github.sha }}","expected_status":"fail"}}'