name: Trigger Playwright Tests
on:
  workflow_dispatch: 
  push:
    branches: 
      - main

jobs:
  trigger-playwright-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright Tests
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository_owner }}/playwright-e2e-tests/dispatches \
            -d '{"event_type": "run-pw-tests", "client_payload": {"cy_commit_sha": "${{ github.sha }}"'on   